In [83]:
# Домашнє завдання №1 (Модуль 1. Знайомство з Data Science)

#Імпорт модулів

In [84]:
import numpy as np

# 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
# Натура́льні чи́сла --- це числа, що виникають природним чином при лічбі. Це числа: 1,2,...10 ... 


In [85]:
vector = np.arange(1, 11) # функція бібліотеки NumPy,створює масив цілих чисел у вказаному діапазоні.
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


# 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [86]:
matrix = np.zeros((3, 3))  # функція бібліотеки NumPy, яка створює масив із заданими розмірами, заповнений нулями.
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [87]:
random_matrix = np.random.randint(1, 11, (5, 5)) # функція бібліотеки NumPy, яка створює масив заданого розміру (в нашому випадку 5 на 5 ) , 
# заповнений його випадковими цілими числами з вказаного діапазону.(внашому випадку від 1 до 11(невключно)) 
print(random_matrix)

[[ 2  6  1  7  3]
 [ 9  3  5  1  8]
 [ 2  2 10  8  5]
 [ 1  7  1  6  5]
 [ 5  7  6  2  1]]


# 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [88]:
random_matrix = np.random.rand(4, 4) # Функція np.random.rand() генерує масив із випадковими числами, рівномірно розподіленими в діапазоні від 0 до 1.
print(random_matrix)

[[0.03303709 0.48257356 0.30660663 0.88916793]
 [0.64192851 0.03122212 0.93667459 0.49335844]
 [0.9002579  0.84610579 0.23730215 0.4644936 ]
 [0.00202136 0.60172278 0.69318514 0.47320201]]


# 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

    5.1 Створення масивів

In [89]:
array1 = np.random.randint(1, 11, 5) # генерує вказану кількість (в нашому випадку 5) випадкових цілих чисел у діапазоні(в нашому випадку від 1 до 10 включно.)
array2 = np.random.randint(1, 11, 5)

print("Масив 1:", array1)
print("Масив 2:", array2)

Масив 1: [5 9 3 8 3]
Масив 2: [10  1  7  8  5]


5.2 Поелементні операції з двома масивами(Додавання, віднімання, множення)

In [90]:
# Виконаємо поелементне  додавання
addition_result = array1 + array2
print("Результат додавання:", addition_result)

# Виконаємо поелементне  віднімання
subtraction_result = array1 - array2
print("Результат віднімання:", subtraction_result)

# Виконаємо поелементне  множення
multiplication_result = array1 * array2
print("Результат множення:", multiplication_result)

Результат додавання: [15 10 10 16  8]
Результат віднімання: [-5  8 -4  0 -2]
Результат множення: [50  9 21 64 15]


# 6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
  Скалярний добуток двох векторів - це число, яке дорівнює сумі добутків відповідних компонент цих векторів.

In [91]:
vector1 = np.random.random(7) # Функція створює масив з вказаною кількістю елементів згенерованих випадковм чином 
vector2 = np.random.random(7)

scalar_product = np.dot(vector1, vector2) # Функція обчислює і повертає скаляриний добудотк вказаних масивів(векторів)

print("Скалярний добуток векторів:", scalar_product)

Скалярний добуток векторів: 1.5159175014318562


# 7. Створіть дві матриці розміром 2x2 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [92]:
matrix1 = np.random.randint(1, 11, (2, 2)) # функція бібліотеки NumPy, яка створює масив заданого розміру (в нашому випадку 2 на 2 ) , 
# заповнений його випадковими цілими числами з вказаного діапазону.(внашому випадку від 1 до 11(невключно))
matrix2 = np.random.randint(1, 11, (2, 3))

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("Результат множення:")
print(result)

Матриця 1:
[[ 6 10]
 [ 2  7]]
Матриця 2:
[[ 7  9  3]
 [ 1  6 10]]
Результат множення:
[[ 52 114 118]
 [ 21  60  76]]


# 8. Створіть матрицю розміром 3x3 , заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

https://uk.wikipedia.org/wiki/%D0%9E%D0%B1%D0%B5%D1%80%D0%BD%D0%B5%D0%BD%D0%B0_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%8F#:~:text=%D0%9E%D0%B1%D0%B5%D1%80%D0%BD%D0%B5%D0%BD%D0%B0%20%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%8F%20%E2%80%94,%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%8F%20%D1%94%20%D0%BD%D0%B5%D0%B2%D0%B8%D1%80%D0%BE%D0%B4%D0%B6%D0%B5%D0%BD%D0%BE%D1%8E.

In [93]:
# Створимо матрицю розміром 3x3 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, (3, 3))

# Виведемо початкову матрицю
print("Початкова матриця:")
print(matrix)

# Знайдемо обернену матрицю
try:
    inverse_matrix = np.linalg.inv(matrix) # Функція повертає обернену матицію до вказаної якщо вона існує і накше повертає помилку *np.linalg.LinAlgError
    print("Обернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("Матриця не має оберненої матриці, оскільки вона може бути сингулярною.")

Початкова матриця:
[[7 5 7]
 [6 3 5]
 [7 1 9]]
Обернена матриця:
[[-0.47826087  0.82608696 -0.08695652]
 [ 0.41304348 -0.30434783 -0.15217391]
 [ 0.32608696 -0.60869565  0.19565217]]


# 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
https://uk.wikipedia.org/wiki/%D0%A2%D1%80%D0%B0%D0%BD%D1%81%D0%BF%D0%BE%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B0_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%8F

In [94]:
matrix = np.random.rand(4, 4) # Функція генерує матрицю вказного розміру(в нашому випадку 4х4) 
# заповниними випадковими дійсними числами з діапазону від 0 до 1

# Виведемо початкову матрицю
print("Початкова матриця:")
print(matrix)

# Транспонуємо матрицю
transposed_matrix = np.transpose(matrix) # Функція виконує транспортування вказаної матирці.

# Виведемо транспоновану матрицю
print("Транспонована матриця:")
print(transposed_matrix)

Початкова матриця:
[[0.33250604 0.15460672 0.00769192 0.82053817]
 [0.47317932 0.74605949 0.18040706 0.62461232]
 [0.11749666 0.47807146 0.24587904 0.95842082]
 [0.51788524 0.33730415 0.46499555 0.12261703]]
Транспонована матриця:
[[0.33250604 0.47317932 0.11749666 0.51788524]
 [0.15460672 0.74605949 0.47807146 0.33730415]
 [0.00769192 0.18040706 0.24587904 0.46499555]
 [0.82053817 0.62461232 0.95842082 0.12261703]]


# 10. Створіть матрицю розміром 3x4  та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

https://programm.top/uk/c-sharp/programs/vector-matrix-multiplication/

In [95]:
# Створимо матрицю розміром 3x4 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, (3, 4))

# Створимо вектор розміром 4 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, 4)

# Виведемо матрицю і вектор
print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)

# Перемножимо матрицю на вектор
result = np.dot(matrix, vector) # Функція повертає скалярного добутку двох масивів або матричного добутку двох матриць.
# (в нашому випадку матричний добуток оскільки множимо матрицю на вектор)

# Виведемо результат
print("Результат перемноження:")
print(result)

Матриця:
[[ 5  9 10  4]
 [ 9  6  2  2]
 [ 2  2  5  4]]
Вектор:
[7 3 8 6]
Результат перемноження:
[166 109  84]


# 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [96]:
# Створимо матрицю розміром 2x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(2, 3)

# Створимо вектор розміром 3 з випадковими дійсними числами від 0 до 1
vector = np.random.rand(3)

# Виведемо матрицю і вектор
print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)

# Перемножимо матрицю на вектор
result = np.dot(matrix, vector)

# Виведемо результат
print("Результат перемноження:")
print(result)

Матриця:
[[0.4585146  0.82168319 0.48687497]
 [0.81498765 0.76977665 0.80911504]]
Вектор:
[0.4224011  0.73210056 0.95194771]
Результат перемноження:
[1.25871131 1.67804082]


# 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [97]:
# Створимо першу матрицю 2x2 з випадковими цілими числами в діапазоні від 1 до 10
matrix1 = np.random.randint(1, 11, (2, 2))

# Створимо другу матрицю 2x2 з випадковими цілими числами в діапазоні від 1 до 10
matrix2 = np.random.randint(1, 11, (2, 2))

# Виведемо обидві матриці
print("Перша матриця:")
print(matrix1)
print("Друга матриця:")
print(matrix2)

# Виконаємо поелементне множення матриць
result = np.multiply(matrix1, matrix2)

# Виведемо результат
print("Результат поелементного множення:")
print(result)

Перша матриця:
[[1 9]
 [4 8]]
Друга матриця:
[[6 8]
 [6 9]]
Результат поелементного множення:
[[ 6 72]
 [24 72]]


# 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [98]:
# Створимо першу матрицю 2x2 з випадковими цілими числами в діапазоні від 1 до 10
matrix1 = np.random.randint(1, 11, (2, 2))

# Створимо другу матрицю 2x2 з випадковими цілими числами в діапазоні від 1 до 10
matrix2 = np.random.randint(1, 11, (2, 2))

# Виведемо обидві матриці
print("Перша матриця:")
print(matrix1)
print("Друга матриця:")
print(matrix2)

# Знайдемо добуток матриць
result = np.dot(matrix1, matrix2)

# Виведемо результат
print("Результат добутку матриць:")
print(result)

Перша матриця:
[[3 2]
 [6 9]]
Друга матриця:
[[ 7  7]
 [10 10]]
Результат добутку матриць:
[[ 41  41]
 [132 132]]


# 14. Створіть матрицю розміром 5x5 , заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [99]:
# Створимо матрицю 5x5 з випадковими цілими числами від 1 до 100
matrix = np.random.randint(1, 101, (5, 5))

# Виведемо матрицю
print("Матриця:")
print(matrix)

# Знайдемо суму елементів матриці
sum_of_elements = np.sum(matrix)

# Виведемо суму
print("Сума елементів матриці: ", sum_of_elements)

Матриця:
[[57 15 53 36 49]
 [51 96 55 30 11]
 [56 58 17 44  1]
 [32 75 77  9 15]
 [48 98 30 68 44]]
Сума елементів матриці:  1125


# 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

Віднімання матриць A і B  - це операція обчислення матриці C , усі елементи якої дорівнюють попарній різниці всіх відповідних елементів матриць 
 A і B , тобто фактичноце полементне віднімання.

In [100]:
# Створимо першу матрицю 4x4 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, (4, 4))

# Створимо другу матрицю 4x4 з випадковими цілими числами від 1 до 10
matrix2 = np.random.randint(1, 11, (4, 4))

# Виведемо обидві матриці
print("Перша матриця:")
print(matrix1)
print("Друга матриця:")
print(matrix2)

# Знайдемо різницю матриць
result = matrix1 - matrix2

# Виведемо результат
print("Різниця матриць:")
print(result)

Перша матриця:
[[ 2  3  3  5]
 [ 9  1  5  3]
 [ 4 10  1  9]
 [ 4 10  8  6]]
Друга матриця:
[[10  2  7  6]
 [ 6  4  8  8]
 [ 9  9 10  2]
 [10  9  4  9]]
Різниця матриць:
[[-8  1 -4 -1]
 [ 3 -3 -3 -5]
 [-5  1 -9  7]
 [-6  1  4 -3]]


# 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [101]:
# Створимо матрицю 3x3 з випадковими дійсними числами в діапазоні від 0 до 1
matrix = np.random.rand(3, 3)

# Виведемо матрицю
print("Матриця:")
print(matrix)

# Знайдемо суму елементів кожного рядка матриці та створимо вектор-стовпчик
sum_of_rows = np.sum(matrix, axis=1, keepdims=True) # Функція np.sum() в бібліотеці Numpy використовується для обчислення суми елементів масиву або матриці.
# Де:
    # a - вхідний масив або матриця
    # axis - вісь, за якою обчислюється сума. Якщо не вказано, сума обчислюється для всіх елементів.
    # keepdims - якщо встановлено в True, то вимірність результуючого масиву зберігається, навіть якщо розмірність за вказаною віссю дорівнює 1.

# Виведемо вектор-стовпчик із сумами
print("Вектор-стовпчик із сумами рядків:")
print(sum_of_rows)

Матриця:
[[0.75282571 0.54248556 0.49546552]
 [0.93009063 0.44228833 0.4698439 ]
 [0.31934871 0.03183029 0.78653269]]
Вектор-стовпчик із сумами рядків:
[[1.79077679]
 [1.84222286]
 [1.13771168]]


# 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [102]:
# Створимо матрицю 3x4 з довільними цілими числами (від -5 до 5)
matrix = np.random.randint(-5, 6, (3, 4))

# Виведемо початкову матрицю
print("Початкова матриця:")
print(matrix)

# Знайдемо матрицю з квадратами чисел
squared_matrix = np.square(matrix) # Функція np.square() в бібліотеці Numpy використовується для обчислення квадрата кожного елемента вхідного масиву або матриці.

# Виведемо матрицю з квадратами чисел
print("Матриця з квадратами чисел:")
print(squared_matrix)

Початкова матриця:
[[-5 -1 -2 -5]
 [ 5  3 -1  4]
 [ 2  0  5  3]]
Матриця з квадратами чисел:
[[25  1  4 25]
 [25  9  1 16]
 [ 4  0 25  9]]


# 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [103]:
# Створимо вектор розміром 4 з випадковими цілими числами від 1 до 50
vector = np.random.randint(1, 51, 4)

# Виведемо початковий вектор
print("Початковий вектор:", vector)

# Знайдемо вектор з квадратними коренями чисел
sqrt_vector = np.sqrt(vector) # Функція np.sqrt() в бібліотеці Numpy використовується для обчислення квадратих коренів кожного елемента вхідного масиву або матриці.


# Виведемо вектор з квадратними коренями
print("Вектор з квадратними коренями чисел:", sqrt_vector)

Початковий вектор: [29 18 40 17]
Вектор з квадратними коренями чисел: [5.38516481 4.24264069 6.32455532 4.12310563]
